### ISSUE TITLE
ImportError: The 'enchant' C library was not found. Please install it via your OS package manager, or use a pre-built binary wheel from PyPI.

### ISSUE THREAD

**Issue by unho** [pyenchant/pyenchant#164]
I get the following when installing `pip install pyenchant<3.0,>=2.0` on my test environment:

> ImportError: The 'enchant' C library was not found. Please install it via your OS package manager, or use a pre-built binary wheel from PyPI.

**Comment by dmerejkowsky** [comment]
Hi there and thanks for the bug report.

I'm the maintainer of this project but it's quite recent so I'll do my best to help you.

First off, are you on Windows? If so, I'm working on a solution to make PyEnchant easier to use on Windows, but it's still a work in progress. See #140, #165 

If not, you should try and follow the instructions from the documentation:
https://pyenchant.github.io/pyenchant/install.html

Hope this helps!

**Comment by MLK97** [comment]
I am getting the same error on Arch Linux.
I have enchant 2.2.7 installed and still get the error.

```bash
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ynpd3vjk/pyenchant/setup.py", line 212, in <module>
        import enchant
      File "/tmp/pip-install-ynpd3vjk/pyenchant/enchant/__init__.py", line 92, in <module>
        from enchant import _enchant as _e
      File "/tmp/pip-install-ynpd3vjk/pyenchant/enchant/_enchant.py", line 145, in <module>
        raise ImportError(msg)
    ImportError: The 'enchant' C library was not found. Please install it via your OS package manager, or use a pre-built binary wheel from PyPI.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by dmerejkowsky** [comment]
I think this is the same bug as #127 

Although I'm just now realizing the error happens *when installing the package from pypi*, and not when using the library later on.

I think it's time to publish a new release on Pypi, so that this does not happen.

**Comment by MLK97** [comment]
> I think it's time to publish a new release on Pypi, so that this does not happen.

That would be invaluable!

**Comment by dmerejkowsky** [comment]
I've just published version 3.0.0a1 on pypi.

Since this is a pre-release, you'll have to be explicit when you install lit from pypi:

```bash
$ pip install pyenchant==3.0.0a1"
```

Beware of the breaking changes, though: https://pyenchant.github.io/pyenchant/changelog.html#breaking-changes

**Comment by Aithys** [comment]
I was able to install from the new version, but still cannot import enchant:

```
C:\Users\gavin>pip list
Package         Version
--------------- ----------
beautifulsoup4  4.8.2
certifi         2019.11.28
chardet         3.0.4
Click           7.0
cycler          0.10.0
futures         3.1.1
goslate         1.5.1
huffman         0.1.2
idna            2.8
kiwisolver      1.1.0
matplotlib      3.1.2
numpy           1.18.1
pip             20.0.2
pyparsing       2.4.6
python-dateutil 2.8.1
requests        2.22.0
six             1.13.0
soupsieve       1.9.5
urllib3         1.25.8

C:\Users\gavin>pip install pyenchant
Collecting pyenchant
  Using cached pyenchant-2.0.0.tar.gz (64 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\gavin\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\gavin\\AppData\\Local\\Temp\\pip-install-q18m7vxu\\pyenchant\\setup.py'"'"'; __file__='"'"'C:\\Users\\gavin\\AppData\\Local\\Temp\\pip-install-q18m7vxu\\pyenchant\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\gavin\AppData\Local\Temp\pip-install-q18m7vxu\pyenchant\pip-egg-info'
         cwd: C:\Users\gavin\AppData\Local\Temp\pip-install-q18m7vxu\pyenchant\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\gavin\AppData\Local\Temp\pip-install-q18m7vxu\pyenchant\setup.py", line 212, in <module>
        import enchant
      File "C:\Users\gavin\AppData\Local\Temp\pip-install-q18m7vxu\pyenchant\enchant\__init__.py", line 92, in <module>
        from enchant import _enchant as _e
      File "C:\Users\gavin\AppData\Local\Temp\pip-install-q18m7vxu\pyenchant\enchant\_enchant.py", line 145, in <module>
        raise ImportError(msg)
    ImportError: The 'enchant' C library was not found. Please install it via your OS package manager, or use a pre-built binary wheel from PyPI.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

C:\Users\gavin>pip install pyenchant==3.0.0a1
Collecting pyenchant==3.0.0a1
  Using cached pyenchant-3.0.0a1-py3-none-any.whl (55 kB)
Installing collected packages: pyenchant
Successfully installed pyenchant-3.0.0a1

C:\Users\gavin>python
Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 01:54:44) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import enchant
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\gavin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\enchant\__init__.py", line 87, in <module>
    from enchant import _enchant as _e
  File "C:\Users\gavin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\enchant\_enchant.py", line 161, in <module>
    raise ImportError(msg)
ImportError: The 'enchant' C library was not found and needs to be installed.
See  https://pyenchant.github.io/pyenchant/install.html
for details

>>>
```

**Comment by dmerejkowsky** [comment]
Sorry, restoring windows support is still a work in progress. See #140, #165 

It's a bit harder than expected ....

**Comment by alex-betis** [comment]
FYI, Alpine linux is now 3.10, and points to enchant 1.6.0-r14. This version is no longer recognized by pyenchant and breaks as noted in this bug report. I tried the 3.0.0a1 , same result.

**Comment by dmerejkowsky** [comment]
@Aithys: forgot to tell you: windows support is back since 3.0.0, can you give it a shot?

@alex-betis : can you install the latest release (3.0.1 at this time), run the commands mentioned in the [troubleshooting](https://pyenchant.github.io/pyenchant/install.html#troubleshooting) section in the website and report the results back here?

**Comment by dmerejkowsky** [comment]
_Update_: I've checked with an alpine docker image and it everything seems to work fine:

```
$ docker run -it alpine
# apk add python3 enchant aspell aspell-en
# python3 -m pip install pyenchant
# python3 -c 'import enchant ; print(enchant.list_dicts())'
[('en', <Enchant: Aspell Provider>), ...)]
```

**Comment by alex-betis** [comment]
I run python:3.8.2-alpine. Here is what I get:
```
$ sudo docker run -it python:3.8.2-alpine /bin/sh
# apk add enchant aspell aspell-en
# pip3 install pyenchant
# export PYENCHANT_VERBOSE_FIND=whatever
# python3 -c 'import enchant'
pyenchant:: looking in system
pyenchant:: with name enchant-2
pyenchant:: with name libenchant-2
pyenchant:: with name enchant
pyenchant:: with name libenchant
pyenchant:: with name enchant-1
pyenchant:: with name libenchant-1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/enchant/__init__.py", line 81, in <module>
    from enchant import _enchant as _e
  File "/usr/local/lib/python3.8/site-packages/enchant/_enchant.py", line 156, in <module>
    raise ImportError(msg)
ImportError: The 'enchant' C library was not found and maybe needs to be installed.
See  https://pyenchant.github.io/pyenchant/install.html
for details
```

Now, guess what, I pulled a virgin alpine image just like you did, and indeed, it works. :face_with_head_bandage:

**Comment by dmerejkowsky** [comment]
@alex-betis I think I found the root cause. It's a [know-bug](https://github.com/docker-library/python/issues/111) in alpine-based python images.

**Comment by Aithys** [comment]
@dmerejkowsky Can confirm its working fine on Windows now - thanks!

**Comment by dmerejkowsky** [comment]
Let's close this, then.
